name: Format ydb/core/tx
description: Check that there is no clang-format diff for ydb/core/tx

runs:
  using: "composite"
  steps:
  - name: Format
    shell: bash
    run: |
      cd ../ydb
      git diff --diff-filter=ACMRT --name-only -- ./ydb/core/tx | xargs -n1 clang-format-17 -style=file -dry-run -Werror 2> clang-format-diff.txt
      if [ -s clang-format-diff.txt ]; then
          echo "Format changed"
          exit 1
      fi
  - name: report Format failed
    if: ${{ failure() }}
    shell: bash
    run: |
      # cat ../ydb/clang-format-diff.txt >> some output
      echo "# Format failed" >> $GITHUB_STEP_SUMMARY
  - name: report Build cancelled
    if: ${{ cancelled() }}
    shell: bash
    run: |
      echo "# Format cancelled" >> $GITHUB_STEP_SUMMARY
